spring:
 profiles:
  active: dev
 http:
  encoding:
   force: true
 datasource:    
   driver-class-name: com.mysql.jdbc.Driver    
   url: jdbc:mysql://localhost:3306/springboot    
   username: root    
   password: root
 rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: admin
  password: admin
  virtual-host: /
  publisher-confirms: true
  listener:
   simple:
    prefetch: 1 #0为轮询，1为分发默认分发          
mybatis:
 mapper-locations: classpath:mybatis/mapper/*.xml
 config-location: classpath:mybatis/mybatis-config.xml
 
 