spring:
 profiles:
  active: dev
 http:
  encoding:
   force: true
 rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: admin
  password: admin
  virtual-host: /
  publisher-confirms: true
  listener:
   simple:
    prefetch: 1 #0为轮询，1为分发默认分发          
    # Redis 配置信息
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
#    password:
  timeout: 3000
  jedis:
   pool:   
    max-idle: 200
    max-wait: 1000
 data:
  mongodb:
    uri: mongodb://localhost:27017/local
    #uri: mongodb://user:pwd@ip1:port1,ip2:port2/database   
mybatis:
 mapper-locations: classpath:mybatis/mapper/*.xml
 config-location: classpath:mybatis/mybatis-config.xml
 
 